version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: formatie_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      # Koppel de huidige map (waar index.html in staat) aan de Nginx html-map
      - ./:/usr/share/nginx/html:ro
